import html2canvas from 'html2canvas';

// Helper: Download a Blob
const downloadBlob = (blob, filename) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};

// 1. Export as JSON
export const exportToJson = (components, connections, filename = 'system-design.json') => {
    const data = {
        meta: {
            version: '1.0',
            exportedAt: new Date().toISOString(),
            platform: 'Intervyu System Design'
        },
        components,
        connections
    };
    const jsonStr = JSON.stringify(data, null, 2);
    const blob = new Blob([jsonStr], { type: 'application/json' });
    downloadBlob(blob, filename);
};

// 2. Export as PNG
export const exportToPng = async (elementId, filename = 'system-design.png') => {
    const element = document.getElementById(elementId);
    if (!element) {
        console.error('Canvas element not found');
        return;
    }

    try {
        const canvas = await html2canvas(element, {
            scale: 2, // High resolution
            useCORS: true,
            backgroundColor: '#f9fafb', // Ensure background is not transparent (bg-gray-50)
            ignoreElements: (node) => {
                // Ignore toolbar or specific controls if marked with class 'no-export'
                return node.classList.contains('no-export');
            }
        });

        canvas.toBlob((blob) => {
            if (blob) downloadBlob(blob, filename);
        }, 'image/png');
    } catch (err) {
        console.error('PNG Export failed:', err);
    }
};

// 3. Generate Markdown Spec
export const generateSpec = (components, connections) => {
    // Generate a quick summary
    const componentList = components.map(c => `- **${c.data.label}** (${c.type}): ${c.data.implementation || 'Generic'}`).join('\n');

    // Simple logic (could import calculateArchitectureSummary if needed, but we keep it standalone here for speed)
    const criticalComponents = components.filter(c => c.type === 'service' || c.type === 'database');
    const spofWarning = criticalComponents.some(c => (c.data?.scaling?.instances || 1) < 2)
        ? "**Warning**: Some critical components represent Single Points of Failure (1 instance)."
        : "Redundancy checks passed.";

    return `# System Architecture Specification

**Date**: ${new Date().toLocaleDateString()}
**Generated By**: Intervyu Architecture Engine

## 1. Executive Summary
This document outlines the proposed high-level architecture. The system consists of ${components.length} components connected via ${connections.length} data flows.

## 2. Component Inventory
${componentList}

## 3. Reliability Analysis
${spofWarning}

## 4. Data Flow
${connections.map((c, i) => {
        const src = components.find(x => x.id === c.from)?.data.label || c.from;
        const tgt = components.find(x => x.id === c.to)?.data.label || c.to;
        return `${i + 1}. **${src}** → **${tgt}**`;
    }).join('\n')}

---
*Auto-generated by Intervyu*
`;
};

// 4. Save/Load to Local Storage
export const saveToLocal = (components, connections) => {
    const data = {
        components,
        connections,
        savedAt: Date.now()
    };
    localStorage.setItem('saved_design', JSON.stringify(data));
    return new Date(data.savedAt).toLocaleTimeString();
};

export const loadFromLocal = () => {
    const raw = localStorage.getItem('saved_design');
    if (!raw) return null;
    try {
        return JSON.parse(raw);
    } catch (e) {
        console.error("Failed to load design", e);
        return null;
    }
};
